FROM python:3.10-slim

WORKDIR /app

# Copy the load generator script
COPY load-generator.py .

# Run the load generator
ENTRYPOINT ["python", "load-generator.py"]
# We pass arguments via the deployment args
CMD ["--url", "http://productpage.bookinfo.svc.cluster.local:9080/productpage", "--header-rate", "0.2"]
